### ISSUE TITLE
Updates to "request to join"

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_db#726]
**User-supplied information**
Currently, there is a discrepancy depending on where a user requests to join an account - during the registration process, or in the registry.

If a user requests to join an account during the **registration** process, they are able to request a particular role and include a message.
<img width="706" alt="Request to join from registration" src="https://user-images.githubusercontent.com/49764220/208696840-547525b4-06aa-436f-a5a4-78cf252c0dd0.png">

Email admin receives
<img width="857" alt="Request sent during registration - email" src="https://user-images.githubusercontent.com/49764220/208698343-f6ee6ed4-ec99-48f2-9335-2888c3765359.png">

On member request page
<img width="1427" alt="Request sent during registration - Hub" src="https://user-images.githubusercontent.com/49764220/208698363-367d3b61-8f01-4734-841c-0bb45e09be67.png">

If a user requests to join an account in the **registry**, they only send a request, and are not able to select their requested role or include a message.
<img width="538" alt="Request to join from registry" src="https://user-images.githubusercontent.com/49764220/208697073-d4193a73-a718-4dea-a801-c51eb9747446.png">

Email admin receives
<img width="853" alt="Request sent from registry - email" src="https://user-images.githubusercontent.com/49764220/208698393-3dc9c7ed-4154-4711-8b4f-8679c01b9b75.png">

On member request page
<img width="1436" alt="Request sent from registry - Hub" src="https://user-images.githubusercontent.com/49764220/208698411-80f23240-9f74-417a-ac3f-cf90191762ff.png">

It would be great to keep the "Just checking" modal, but maybe there could be a second modal for users to request their role and include a message when requesting from the registry?

**System-supplied information**
It would also be ideal to include more information about the user who requested to join, maybe their position and affiliation (as supplied in their profile). I think we might consider also including their email, unless there is another way that the admin could send a message / email the requester, since as of now, there would be no way for the admin to ask for clarification.

**Making a note to consider what content needs to be updated after hearing what is possible! Thank you :)**

**Comment by birbjam** [comment]
I updated this, the modals are now identical:
<img width="880" alt="Screen Shot 2022-12-20 at 2 15 08 PM" src="https://user-images.githubusercontent.com/41635757/208777206-dd272731-81fa-48b8-a1e3-d760c0f7563b.png">


> System-supplied information
It would also be ideal to include more information about the user who requested to join, maybe their position and affiliation (as supplied in their profile). I think we might consider also including their email, unless there is another way that the admin could send a message / email the requester, since as of now, there would be no way for the admin to ask for clarification.


Email can possibly be added to this card (might have to talk about that with the team first) but all the other information is already included on that card: Position, affiliations, etc.
